.Dd Nov 20, 2019
.Dt index 1
.Sh Manual Pages
UNIX manual pages for projects by
.Lk https://github.com/troglobit Troglobit Software .
.Bl -tag -width Lk -offset indent
.It Lk /man1/index.html 1: Em User commands
.It Lk /man3/index.html 3: Em Library functions
.It Lk /man5/index.html 5: Bf -emphasis Files; Ef describes file formats used
.It Lk /man8/index.html 8: Em Superuser and system administration commands
.El
